version: '3'

volumes:
  var_lib_postgresql_data:

networks:
  netmain:
    driver: bridge
 

services:

  storage:
      image: ${PROJECT}_storage
      expose:
        - "5432"    
      ports:
        - "5432:5432"
      networks:
        - netmain
      volumes:
        - var_lib_postgresql_data:/var/lib/postgresql/data
      # .............................................
      restart: always

